apiVersion: v1
kind: ConfigMap
metadata:
  name: forecasting-config
  namespace: forecasting
data:
  SERVICE_NAME: "forecasting-service"
  AWS_REGION: "us-east-1"
  SAGEMAKER_ENDPOINT: "assessment4-ying-forecasting-endpoint"

---
apiVersion: v1
kind: Secret
metadata:
  name: forecasting-secret
  namespace: forecasting
type: Opaque
stringData:
  API_TOKEN: "assessment4-demo-token"